---
version: "3"

env:
  HOST:
    sh: "echo $(hostname -s) | tr '[:upper:]' '[:lower:]'"

vars:
  dir: '{{.dir | default .ROOT_DIR}}'
  user: '{{.user | default .USER}}'
  host: '{{.host | default .HOST}}'

includes:
  g: .taskfiles/git
  h: .taskfiles/home-manager
  n: .taskfiles/nixos

tasks:
  default:
    silent: true
    cmds: ["task -l"]

  bs:
    desc: Bootstrap the system
    silent: true
    cmds:
      - task: n:switch
      - task: h:switch
