#!/bin/sh

bspc config border_width        5

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

if [[ $(hostname) == 'Mimic' ]]; then
    bspc monitor LVDS1 -d 1 2 3 4 5
    bspc config window_gap 10
elif [[ $(hostname) == 'mfinzgar' ]]; then
    bspc monitor HDMI-1 -d 1 2 3 4 5
    bspc monitor DP-2 -d 6 7 8
    bspc config window_gap 15
    bspc rule -a Firefox state=floating
elif [[ $(hostname) == 'Magneto' ]]; then
    bspc monitor DVI-I-1 -d 1 2 3 4 5
    bspc monitor HDMI-0 -d 6 7 8
    bspc config window_gap 20
fi

bspc config normal_border_color '#111111'
bspc config focused_border_color '#d3d3d3'
bspc config presel_border_color '#719d72'
bspc config normal_sticky_border_color '#8abeb7'
bspc config focused_sticky_border_color '#f0c674'
bspc config urgent_border_color '#b76969'

bspc rule -a Spotify desktop=^4 state=floating
bspc rule -a mpv state=floating
bspc rule -a Pinentry-gtk-2 state=floating
bspc rule -a Shutter state=floating

$HOME/.config/bspwm/panel &
