#!/bin/sh

bspc config border_width              5

bspc config split_ratio               0.5
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config focus_by_distance         true
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config pointer_modifier          mod1

bspc config normal_border_color '#111111'
bspc config focused_border_color '#d3d3d3'
bspc config presel_border_color '#719d72'
bspc config normal_sticky_border_color '#8abeb7'
bspc config focused_sticky_border_color '#f0c674'
bspc config urgent_border_color '#b76969'
bspc config top_padding 25

bspc rule -a mpv state=floating
bspc rule -a Pinentry-gtk-2 state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Tk  state=floating

if [[ $(hostname) == 'Mimic' ]]; then
    bspc monitor eDP1 -d 1 2 3 4 5
    bspc config window_gap 10

    polybar mimic_main &
elif [[ $(hostname) == 'mfinzgar' ]]; then
    bspc monitor HDMI-1 -d 1 2 3 4 5
    bspc monitor DP-2 -d 6 7 8
    bspc config window_gap 10
    bspc rule -a Firefox state=floating
    bspc rule -a Google-chrome state=floating
    bspc rule -a Google-chromium state=floating
    bspc rule -a Chromium state=floating

    polybar mfinzgar_main &
    polybar mfinzgar_secondary &
elif [[ $(hostname) == 'Wolverine' ]]; then
    bspc monitor DVI-I-1 -d 1 2 3 4 5
    bspc monitor HDMI-0 -d 6 7 8
    bspc config window_gap 20

    polybar wolverine_main &
    polybar wolverine_secondary &
fi
