#!/bin/sh

bspc config split_ratio               0.5
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config focus_by_distance         true
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config pointer_modifier          mod1
bspc config pointer_follows_monitor   true

bspc config normal_border_color '#111111'
bspc config focused_border_color '#d3d3d3'
bspc config presel_border_color '#719d72'
bspc config normal_sticky_border_color '#8abeb7'
bspc config focused_sticky_border_color '#f0c674'
bspc config urgent_border_color '#b76969'

bspc config single_monocle true
bspc config window_gap 10
bspc config top_padding 20
bspc config border_width 2

bspc rule -a mpv state=floating
bspc rule -a Pinentry-gtk-2 state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Tk  state=floating
bspc rule -a usbguard-applet-qt state=floating
bspc rule -a Blueman-manager state=floating

if [[ $(hostname) == 'Wolverine' ]]; then
    export MONITOR=HDMI-0
    bspc monitor $MONITOR -d 1 2 3 4 5

    polybar primary &
elif [[ $(hostname) == 'Lockheed' ]]; then
    export MONITOR=eDP1
    bspc monitor $MONITOR -d 1 2 3 4 5

    polybar primary &
fi
