#! /bin/sh

source $(dirname $0)/panel_config

bspc config top_padding $PANEL_HEIGHT
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

PANEL_FIFO=/tmp/bspwm_

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

# Set X offset of the bar
CUR_X_OFFSET=0

# How many monitors are we displaying bar on?
num_mon=$(bspc query -M)

for i in $num_mon; do
    MONITOR=$(bspc query -T -m $i | jq -r .name)

    # Remove old panel_fifo and create a new one
    [ -e "$PANEL_FIFO$MONITOR" ] && rm "$PANEL_FIFO$MONITOR"
    mkfifo "$PANEL_FIFO$MONITOR"

    xtitle -sf 'T%s' > "$PANEL_FIFO$MONITOR" &

    # Get bspwm information for current monitor
    bspc subscribe |\
        grep -oE "[Mm]$MONITOR[^TM]*[TML]" --line-buffered |\
        while read line; do echo W$line; done \
            > "$PANEL_FIFO$MONITOR" &

    # Output extra scripts to the panel_fifo
    ~/.config/bspwm/panel_status_$MONITOR > "$PANEL_FIFO$MONITOR" &

    # Get current monitor width
    CUR_MON_WIDTH=$(bspc query -T -m $MONITOR | jq -r .rectangle.width)
    PANEL_GEO="${CUR_MON_WIDTH}x${PANEL_HEIGHT}+${CUR_X_OFFSET}+0"


    # Running bar
    cat "$PANEL_FIFO$MONITOR" | ~/.config/bspwm/panel_lemon |\
        lemonbar -g $PANEL_GEO \
        -F "#FF$FOREGROUND_COLOR" -B "#FF$BACKGROUND_COLOR" -f "$FONT" -f "$FONT2"\
        | while read line; do eval "$line"; done &

    # New X Offset
    CUR_X_OFFSET=$(expr $CUR_X_OFFSET + $CUR_MON_WIDTH)


done

wait
