#! /bin/sh

# for icons $(printf '%b' "\ue0e1")

source $(dirname $0)/panel_config

volume(){
    VOLUME=$(pulseaudio-ctl full-status | awk '{split($0, array, " ")} END{print array[1]}')
    MUTE=$(pulseaudio-ctl full-status | awk '{split($0, array, " ")} END{print array[2]}')
    if [ "$MUTE" == "yes" ]; then
        echo "%{F#FF$RED_COLOR A:pulseaudio-ctl mute:}vol $VOLUME%%{A F-}"
    else echo "%{F#FF$WHITE_COLOR A:pulseaudio-ctl mute:}vol %{F}$VOLUME%%{A}"
    fi
}

mpd(){
    STATUS=$(mpc current)
    if [ "$STATUS" != "" ]; then
        echo "%{F#FF$WHITE_COLOR A:mpc toggle: A3:mpc stop:}mpd %{F}$STATUS%{A A} $SEP "
    else echo ""
    fi
}

spotify(){
    STATUS=$(playerctl status)
    if [ "$STATUS" == "Playing" ]; then
        echo "%{F#FF$GREEN_COLOR A:playerctl play-pause: A3:playerctl stop:}$(printf '%b' "\ue205")%{F-} $(playerctl metadata xesam:artist) - $(playerctl metadata xesam:title)%{A A} $SEP "
    elif [ "$STATUS" == "Paused" ]; then
        echo "%{F#FF$YELLOW_COLOR A:playerctl play-pause: A3:playerctl stop:}$(printf '%b' "\ue205")%{F-} $(playerctl metadata xesam:artist) - $(playerctl metadata xesam:title)%{A A} $SEP "
    else echo ""
    fi
}

wifi_ssid(){
    NAME=$(iwconfig wlp0s29u1u4 | grep 'ESSID:' | awk '{print $4}' | sed 's/ESSID://g' | sed 's/"//g')
    if [ "$NAME" == "" ]; then
        echo "%{F#FF$RED_COLOR}wifi no conn%{F}"
    else echo "%{F#FF$WHITE_COLOR}wifi %{F}$NAME"
    fi
}

transmission() {
    ACTIVETORR=$(transmission-remote -l | egrep '(Downloading|Up & Down)' | wc -l)
    echo "%{F#FF$WHITE_COLOR}dl %{F}$ACTIVETORR"
}

while :; do
    echo "S%{r}$(mpd)$(volume) %{B-}"
    sleep 2
done
