#! /bin/sh
#
# bar input parser for bspwm

NORMIFS=$IFS
FIELDIFS=':'

source $(dirname $0)/panel_config

while read -r line ; do
    case $line in
        S*)
            # conky
            sys_infos="${line#?}"
            ;;
        #M*)
        #    spotify="${line#?}"
        #    ;;
        #C*)
            ##clock
            #clock="${line#?}"
            #clock="%{F$CLOCK_BG}⮂%{F- B$CLOCK_BG A:dzen_popup_toggle.sh calendar:} ${clock} %{A B- F$CLOCK_BG}⮀%{F-}"
            #;;
        T*)
            if [[ ${line#?} == "" ]]; then
                title=""
            else title="%{F$RED_COLOR}$(printf "%b" "\ue135")%{F-} %{A:bspc window -t floating:}$(echo ${line#?} | sed 's^\(.\{40\}\).*^\1...^')%{A}"
            fi
            ;;
        W*)
            wm_infos=""
            IFS=$FIELDIFS
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                case $item in
                    [OoFfUu]*)
                        name=${item#?}
                        case $name in
                            1) DESK_ICON="" ;;
                            2) DESK_ICON="" ;;
                            3) DESK_ICON="" ;;
                            4) DESK_ICON="" ;;
                            5) DESK_ICON="" ;;
                        esac
                        case $item in
                            O*)
                                # focused occupied desktop
                                desk="%{F$FOREGROUND_COLOR}$DESK_ICON $(printf '%b' "\ue056")%{F-}"
                                ;;
                            F*)
                                # focused free desktop
                                desk="%{F$FOREGROUND_COLOR}$DESK_ICON $(printf '%b' "\ue056")%{F-}"
                                ;;
                            U*)
                                # focused urgent desktop
                                desk="%{F$MAGENTA_COLOR}$DESK_ICON $(printf '%b' "\ue056")%{F-}"
                                ;;
                            o*)
                                # occupied desktop
                                desk="%{F$FOREGROUND_COLOR}$DESK_ICON $(printf '%b' "\ue0e6")%{F-}"
                                ;;
                            f*)
                                # free desktop
                                desk="%{F$RED2_COLOR}$DESK_ICON $(printf '%b' "\ue0e6")%{F-}"
                                ;;
                            u*)
                                # urgent desktop
                                desk="%{F$MAGENTA_COLOR}$DESK_ICON $(printf '%b' "\ue056")%{F-}"
                                ;;
                        esac
                        wm_infos="${wm_infos}%{A:bspc desktop -f ${name}:}${desk}%{A} "
                        ;;
                    [L]*)
                        if [[ ${item#?} == "T" ]]; then
                            layout="%{F$FOREGROUND_COLOR B$YELLOW2_COLOR A:bspc desktop -l monocle: A3:bspc desktop -R 90:}  $(printf "%b" "\ue131")  %{A A B F-}"
                        else layout="%{F$FOREGROUND_COLOR B$YELLOW2_COLOR A:bspc desktop -l tiled:}  $(printf "%b" "\ue130")  %{A B F-}"
                        fi
                        ;;
                esac
                shift
            done
            IFS=$NORMIFS
            ;;
    esac
    printf "%s\n" "%{l B$RED_COLOR}  $wm_infos  %{B-}  $title $sys_infos"
done
