#! /bin/sh

source $(dirname $0)/panel_config

bspc config top_padding $PANEL_HEIGHT
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

PANEL_FIFO=~/.config/bspwm/fifo_

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

# Set X offset of the bar
CUR_X_OFFSET=0

# How many monitors are we displaying bar on?
num_mon=$(bspc query -M)

for i in $num_mon; do

    # Remove old panel_fifo and create a new one
    [ -e "$PANEL_FIFO$i" ] && rm "$PANEL_FIFO$i"
    mkfifo "$PANEL_FIFO$i"

    xtitle -sf 'T%s' > "$PANEL_FIFO$i" &

    # Get bspwm information for current monitor
    bspc control --subscribe |\
        grep -oE "[Mm]$i[^TM]*[TML]" --line-buffered |\
        while read line; do echo W$line; done \
            > "$PANEL_FIFO$i" &

    # Output extra scripts to the panel_fifo
    ~/.config/bspwm/panel_status_$i > "$PANEL_FIFO$i" &

    # Get current monitor width
    CUR_MON_WIDTH=$(bspc query -T -m $i | grep -oE "[0-9]{2,6}" | head -n 1)
    PANEL_GEO="${CUR_MON_WIDTH}x${PANEL_HEIGHT}+${CUR_X_OFFSET}+0"


    # Running bar
    cat "$PANEL_FIFO$i" | ~/.config/bspwm/panel_lemon |\
        lemonbar -g $PANEL_GEO \
        -B "#ee$FOREGROUND_COLOR" -F "#FF$BACKGROUND_COLOR" -f "$FONT1" -f "$FONT2" \
        | while read line; do eval "$line"; done &

    # New X Offset
    CUR_X_OFFSET=$(expr $CUR_X_OFFSET + $CUR_MON_WIDTH)


done

wait
