#! /bin/sh
#
# bar input parser for bspwm

NORMIFS=$IFS
FIELDIFS=':'

source $(dirname $0)/panel_config

while read -r line ; do
    case $line in
        S*)
            sys_infos="${line#?}"
            ;;
        T*)
            if [[ ${line#?} == "" ]]; then
                title="%{F#FF$RED_COLOR}$(printf "%b" "\ue0a1")%{F-} $(uname -r)"
            else title="%{F#FF$RED_COLOR}$(printf "%b" "\ue135")%{F-} %{A:bspc window -t floating: A3:bspc desktop -R 90:}$(echo ${line#?} | sed 's^\(.\{40\}\).*^\1...^')%{A A-}"
            fi
            ;;
        W*)
            wm_infos=""
            IFS=$FIELDIFS
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                case $item in
                    [OoFfUu]*)
                        name=${item#?}
                        case $item in
                            O*)
                                # focused occupied desktop
                                desk="%{F#FF$FOREGROUND_COLOR B#FF$CYAN2_COLOR} $name %{B- F-}"
                                ;;
                            F*)
                                # focused free desktop
                                desk="%{F#FF$FOREGROUND_COLOR B#FF$CYAN2_COLOR} $name %{B- F-}"
                                ;;
                            U*)
                                # focused urgent desktop
                                desk="%{F#FF$FOREGROUND_COLOR B#FF$RED_COLOR} $name %{B- F-}"
                                ;;
                            o*)
                                # occupied desktop
                                desk="%{F#FF$FOREGROUND_COLOR B#FF$BLACK2_COLOR} $name %{B- F-}"
                                ;;
                            f*)
                                # free desktop
                                desk="%{F#FF$FOREGROUND_COLOR} $name %{F-}"
                                ;;
                            u*)
                                # urgent desktop
                                desk="%{F#FF$RED_COLOR} $name %{F-}"
                                ;;
                        esac
                        wm_infos="${wm_infos}%{A:bspc desktop -f ${name}:}${desk}%{A}"
                        ;;
                esac
                shift
            done
            IFS=$NORMIFS
            ;;
    esac
    printf "%s\n" "%{l}$wm_infos $sys_infos"
done
