#!/usr/bin/bash

source $(dirname $0)/config

C_FOCUSED=$RED2_COLOR
C_UNFOCUSED=$BACKGROUND_COLOR

xdesktop -s | \
while read line; do
    case $line in
        1) echo "%{c}%{B#FF$C_FOCUSED}%{A:wmctrl -s 0:}$DESK_INDICATOR%{A}%{B-}   %{B#FF$C_UNFOCUSED}%{A:wmctrl -s 1:}$DESK_INDICATOR%{A}%{B-}   %{B#FF$C_UNFOCUSED}%{A:wmctrl -s 2:}$DESK_INDICATOR%{A}%{B-}   %{B#FF$C_UNFOCUSED}%{A:wmctrl -s 3:}$DESK_INDICATOR%{A}%{B-}" ;;
        2) echo "%{c}%{B#FF$C_UNFOCUSED}%{A:wmctrl -s 0:}$DESK_INDICATOR%{A}%{B-}   %{B#FF$C_FOCUSED}%{A:wmctrl -s 1:}$DESK_INDICATOR%{A}%{B-}   %{B#FF$C_UNFOCUSED}%{A:wmctrl -s 2:}$DESK_INDICATOR%{A}%{B-}   %{B#FF$C_UNFOCUSED}%{A:wmctrl -s 3:}$DESK_INDICATOR%{A}%{B-}" ;;
        3) echo "%{c}%{B#FF$C_UNFOCUSED}%{A:wmctrl -s 0:}$DESK_INDICATOR%{A}%{B-}   %{B#FF$C_UNFOCUSED}%{A:wmctrl -s 1:}$DESK_INDICATOR%{A}%{B-}   %{B#FF$C_FOCUSED}%{A:wmctrl -s 2:}$DESK_INDICATOR%{A}%{B-}   %{B#FF$C_UNFOCUSED}%{A:wmctrl -s 3:}$DESK_INDICATOR%{A}%{B-}" ;;
        4) echo "%{c}%{B#FF$C_UNFOCUSED}%{A:wmctrl -s 0:}$DESK_INDICATOR%{A}%{B-}   %{B#FF$C_UNFOCUSED}%{A:wmctrl -s 1:}$DESK_INDICATOR%{A}%{B-}   %{B#FF$C_UNFOCUSED}%{A:wmctrl -s 2:}$DESK_INDICATOR%{A}%{B-}   %{B#FF$C_FOCUSED}%{A:wmctrl -s 3:}$DESK_INDICATOR%{A}%{B-}" ;;
    esac
done \
| lemonbar -b -d -g 400x10+760+0 -f $FONT -F "#FF$RED_COLOR" -B "#00$BLACK_COLOR" \
| while read line; do eval "$line"; done
