#! /bin/sh

bspc config border_width        2
bspc config window_gap         10

bspc config split_ratio         0.6
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d 1 2 3 4 5

bspc config normal_border_color '#1d1f21'
bspc config focused_border_color '#c5c8c6'

~/.config/bspwm/panel &
