#! /bin/sh
#
# bar input parser for bspwm  Tuesday, 01 July 2014 22:57

NORMIFS=$IFS
FIELDIFS=':'

source $(dirname $0)/panel_config

while read -r line ; do
    case $line in
        S*)
            # conky
            sys_infos="${line#?}"
            ;;
        #M*)
        #    spotify="${line#?}"
        #    ;;
        #C*)
            ##clock
            #clock="${line#?}"
            #clock="%{F$CLOCK_BG}⮂%{F- B$CLOCK_BG A:dzen_popup_toggle.sh calendar:} ${clock} %{A B- F$CLOCK_BG}⮀%{F-}"
            #;;
        T*)
            if [[ ${line#?} == "" ]]; then
                title=""
            else title="$SEP %{F$COLOR2}$(printf "%b" "\ue135")%{F-} %{A:bspc window -t floating:}$(echo ${line#?} | sed 's^\(.\{40\}\).*^\1...^')%{A}"
            fi
            ;;
        W*)
            wm_infos=""
            IFS=$FIELDIFS
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                case $item in
                    [OoFfUu]*)
                        name=${item#?}
                        case $item in
                            O*)
                                # focused occupied desktop
                                desk="%{F$COLOR1}$(printf "%b" "\ue000")%{F-}"
                                ;;
                            F*)
                                # focused free desktop
                                desk="%{F$COLOR1}$(printf "%b" "\ue000")%{F-}"
                                ;;
                            U*)
                                # focused urgent desktop
                                desk="%{F$COLOR1}$(printf "%b" "\ue000")%{F-}"
                                ;;
                            o*)
                                # occupied desktop
                                desk="%{F$COLOR3}$(printf "%b" "\ue000")%{F-}"
                                ;;
                            f*)
                                # free desktop
                                desk="%{F#ff555555}$(printf "%b" "\ue076")%{F-}"
                                ;;
                            u*)
                                # urgent desktop
                                desk="%{F$COLOR3}$(printf "%b" "\ue026")%{F-}"
                                ;;
                        esac
                        wm_infos="${wm_infos}%{A:bspc desktop -f ${name}:}${desk}%{A} "
                        ;;
                    [L]*)
                        if [[ ${item#?} == "T" ]]; then
                            layout="%{F$COLOR2}$(printf "%b" "\ue137")%{F-}"
                        else layout="%{F$COLOR2}$(printf "%b" "\u130")%{F-}"
                        fi
                        ;;
                esac
                shift
            done
            IFS=$NORMIFS
            ;;
    esac
    printf "%s\n" "%{l} %{F$COLOR1}%{A:dmenu_run.sh:}$(printf "%b" "\ue0a1")%{F-} $(uname -n)$(printf "%b" "\u2122")%{A} $title%{c} $wm_infos%{r}$sys_infos "
done
