#! /bin/sh

source $(dirname $0)/panel_config

battery(){
    CAPACITY=$(cat /sys/class/power_supply/BAT0/capacity)
    if [ $CAPACITY -lt 20 ]; then
        echo "%{F$COLOR1}$(printf '%b' "\ue037") $CAPACITY%%{F-}"
    else echo "%{F$COLOR2}$(printf '%b' "\ue037")%{F-} $CAPACITY%"
    fi
}

volume(){
    VOLUME=$(pulseaudio-ctl full-status | awk '{split($0, array, " ")} END{print array[1]}')
    MUTE=$(pulseaudio-ctl full-status | awk '{split($0, array, " ")} END{print array[2]}')
    if [ "$MUTE" == "yes" ]; then
        echo "%{F$COLOR1}%{A:pulseaudio-ctl mute:}$(printf '%b' "\ue04f") $VOLUME%%{A F-}"
    else echo "%{F$COLOR2}%{A:pulseaudio-ctl mute:}$(printf '%b' "\ue05d")%{F-} $VOLUME%%{A}"
    fi
}

spotify(){
    STATUS=$(playerctl status)
    if [ "$STATUS" == "Playing" ] || [ "$STATUS" == "Paused" ]; then
        if [ "$STATUS" == "Playing" ]; then
            STAT_COLOR="$COLOR2"
        else STAT_COLOR="$COLOR1"
        fi
        ARTIST=$(playerctl metadata xesam:artist)
        TITLE=$(playerctl metadata xesam:title)
        echo "%{c}%{F$COLOR2}%{A:playerctl play-pause:}%{F$STAT_COLOR}$(printf '%b' "\ue05c")%{F-} $ARTIST - $TITLE%{A}"
    fi
}

wifi_ssid(){
    NAME=$(iwconfig wlp2s0 | grep 'ESSID:' | awk '{print $4}' | sed 's/ESSID://g' | sed 's/"//g')
    if [ "$NAME" == "" ]; then
        echo "%{F$COLOR1}$(printf '%b' "\ue048")%{F-} no conn"
    else echo "%{F$COLOR2}$(printf '%b' "\ue048")%{F-} $NAME"
    fi
}

while :; do
    echo "S$(spotify)%{r} $(wifi_ssid) $SEP $(volume) $SEP $(battery)  %{B#ff2a2a2a}  %{F$COLOR2}$(printf '%b' "\ue01f")%{F-} $(date +'%a %b %d')  %{B#ff333333}  %{F$COLOR2}$(printf '%b' "\ue016")%{F-} $(date +'%H:%M')  %{B-}"
    sleep 1
done