#! /bin/sh
#
# bar input parser for bspwm  Tuesday, 01 July 2014 22:57

NORMIFS=$IFS
FIELDIFS=':'

source $(dirname $0)/panel_config

while read -r line ; do
    case $line in
        S*)
            # conky
            sys_infos="${line#?}"
            ;;
        #A*)
        #    # custom window title using xprop xwinfo
        #    title="%{F$TITLE_FG B-}${PAD}$(xwinfo -c ${line#?} | sed 's@N/A@@')${PAD}%{F- B-}"
        #    ;;
        #C*)
            ##clock
            #clock="${line#?}"
            #clock="%{F$CLOCK_BG}⮂%{F- B$CLOCK_BG A:dzen_popup_toggle.sh calendar:} ${clock} %{A B- F$CLOCK_BG}⮀%{F-}"
            #;;
        #T*)
        #    title=$(echo ${line#?} | sed 's^\(.\{40\}\).*^\1...^')
        #    ;;
        W*)
            wm_infos=""
            IFS=$FIELDIFS
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                case $item in
                    [OoFfUu]*)
                        name=${item#?}
                        case $item in
                            O*)
                                # focused occupied desktop
                                desk="%{F$COLOR1}$(printf "%b" "\ue056")%{F-}"
                                ;;
                            F*)
                                # focused free desktop
                                desk="%{F$COLOR1}$(printf "%b" "\ue056")%{F-}"
                                ;;
                            U*)
                                # focused urgent desktop
                                desk="%{F$COLOR1}$(printf "%b" "\ue056")%{F-}"
                                ;;
                            o*)
                                # occupied desktop
                                desk="%{F$COLOR3}$(printf "%b" "\ue056")%{F-}"
                                ;;
                            f*)
                                # free desktop
                                desk="%{F$COLOR3}$(printf "%b" "\ue0e6")%{F-}"
                                ;;
                            u*)
                                # urgent desktop
                                desk="%{F$COLOR3}$(printf "%b" "\ue056")%{F-}"
                                ;;
                        esac
                        wm_infos="${wm_infos}%{A:bspc desktop -f ${name}:}${desk}%{A} "
                        ;;
                esac
                shift
            done
            IFS=$NORMIFS
            ;;
    esac
    printf "%s\n" "%{l} %{F$COLOR1}$(printf "%b" "\ue0a1")%{F-} $(uname -r)%{c} $wm_infos%{r}$sys_infos "
done
