#!/bin/bash

bspc config top_padding 20
bspc config left_padding 10
bspc config right_padding 10

#FONT1='-*-terminus-medium-*-*-*-12-*-*-*-*-*-*-*'
FONT1='-*-termsyn-medium-*-*-*-13-*-*-*-*-*-*-*'
FONT2='-misc-stlarch-medium-r-normal--10-100-75-75-c-80-iso10646-1'
COLOR1='#ffcc6666'
COLOR2='#fff0c674'
SEP='%{F#ff373b41}>>%{F-}'

workspace(){
	SPACE_NUM=$(bspc query -D -d);
		case "$SPACE_NUM" in
			"1")
				WORKSPACE=" %{F$COLOR1}$(printf '%b' "\ue000")%{F-} $(printf '%b' "\ue001") $(printf '%b' "\ue001") $(printf '%b' "\ue001") $(printf '%b' "\ue001") ";;
			"2")
				WORKSPACE=" $(printf '%b' "\ue001") %{F$COLOR1}$(printf '%b' "\ue000")%{F-} $(printf '%b' "\ue001") $(printf '%b' "\ue001") $(printf '%b' "\ue001") ";;
			"3")
				WORKSPACE=" $(printf '%b' "\ue001") $(printf '%b' "\ue001") %{F$COLOR1}$(printf '%b' "\ue000")%{F-} $(printf '%b' "\ue001") $(printf '%b' "\ue001") ";;
			"4")
				WORKSPACE=" $(printf '%b' "\ue001") $(printf '%b' "\ue001") $(printf '%b' "\ue001") %{F$COLOR1}$(printf '%b' "\ue000")%{F-} $(printf '%b' "\ue001") ";;
			"5")
				WORKSPACE=" $(printf '%b' "\ue001") $(printf '%b' "\ue001") $(printf '%b' "\ue001") $(printf '%b' "\ue001") %{F$COLOR1}$(printf '%b' "\ue000")%{F-} ";;
		esac
	echo $WORKSPACE
}

cmus(){
	STATUS=$(cmus-remote -Q | grep status | awk '{print $2}')
	if [ "$STATUS" == "playing" ]; then
		ARTIST=$(cmus-remote -Q | sed -ne '/artist/s/tag artist //pg')
		TITLE=$(cmus-remote -Q | sed -ne '/title/s/tag title //pg')
		echo "$SEP %{F$COLOR2}$(printf '%b' "\ue05c")%{F-} $ARTIST - $TITLE"
	fi
}

battery(){
	CAPACITY=$(cat /sys/class/power_supply/BAT0/capacity)
	if [ $CAPACITY -lt 20 ]; then
		echo "%{F$COLOR1}$(printf '%b' "\ue037") $CAPACITY%%{F-}"
	else echo "%{F$COLOR2}$(printf '%b' "\ue037")%{F-} $CAPACITY%"
	fi
}

volume(){
	VOLUME=$(pulseaudio-ctl current)
	echo "%{F$COLOR2}$(printf '%b' "\ue050")%{F-} $VOLUME"
}

while :; do
	echo  "%{l} %{F$COLOR1}$(printf '%b' "\ue027")%{F-} $(uname -r) $(cmus)%{c}$(workspace)%{r} $(volume) $SEP $(battery) $SEP %{F$COLOR2}$(printf '%b' "\ue015")%{F-} $(date +'%H:%M') "
	sleep 2 
done | lemonbar -g 1346x20+10+0 -f "$FONT1,$FONT2" -B '#ff1d1f21' -F '#ffc5c8c6'
