#!/bin/bash

case $1 in
    1)
        STATUS1=$(hue lights 1 | cut -d' ' -f5)
        if [ "$STATUS1" == "on" ]; then
            hue lights 1 off
	    notifysend.sh 'hue' 'Lights OFF'
        else
	    hue lights 1 on
	    notify-send.sh 'hue' 'Lights ON'
        fi
        ;;
    2)
        STATUS2=$(hue lights 2 | cut -d' ' -f5)
        if [ "$STATUS2" == "on" ]; then
            hue lights 2 off
	    notify-send.sh 'hue' 'Lights OFF'
        else
	    hue lights 2 on
	    notify-send.sh 'hue' 'Lights ON'
        fi
        ;;
esac
