#!/usr/bin/env bash

shopt -s nullglob globstar

if [ -f $HOME/.dmenurc ]; then
    . $HOME/.dmenurc
fi

typeit=1
if [[ $1 == "--no-type" ]]; then
	typeit=0
	shift
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | dmenu "$@")

[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
	pass show -c "$password" 2>/dev/null
else
	xdotool - <<<"type --clearmodifiers -- $(pass show "$password" | head -n 1)"
fi